### ISSUE TITLE
Understanding about the article

### ISSUE THREAD

**Issue by Antonwxb** [ZrrSkywalker/Point-NN#12]
你好，我对于你们文章中的公式（9）有一些疑问。按照文中所说，这个公式是为了给每个点的特征向量f赋予局部的几何信息。针对公式括号中的部分（不包括element-wise multiply的部分）我的理解是：第一项包含有点的绝对坐标位置信息，第二项包含有点和k近邻范围内均值坐标的相对位置信息，也就是几何信息。如果只是为了达到赋予特征向量局部的几何信息这一目的，那么括号中的部分不就已经达到了这个目的吗？括号中的两项相加可以理解为结合了绝对坐标信息和局部几何信息，为什么还要加element-wise multiply呢？不知道我的表述是否清楚，可能问题有些奇怪因为我只是初学者，希望您能不吝赐教。
另外文章针对3d目标检测只做了室内场景的实验，室外场景和室内场景数据差异还是挺大的，不知道您对您的方法应用于一些室外场景检测框架的效果有没有什么预期或者分析？

**Comment by Cipher-zzz** [comment]
@Antonwxb @ZrrSkywalker 不确定我的理解是否正确，希望作者能就这部分做一些补充。

我感觉再做一次element-wise multiply是为了生成了一个临近点与临近点之间关联信息的矩阵。

类似于Transformer中的QK矩阵相乘。
![image](https://user-images.githubusercontent.com/34538583/236114604-5ef2313d-c85d-4b2d-a8ce-673fb8ea95aa.png)

**Comment by ZrrSkywalker** [comment]
@Antonwxb @Cipher-zzz 感谢对我们工作的兴趣。
@Cipher-zzz 谢谢你的补充，乘法的操作相当于一个对数值量级的reweight，增强更加有几何关联的点的数值，也可以相当于构建了一个关系矩阵，增加让更加相近特征的点的数值

**Comment by Antonwxb** [comment]
@Cipher-zzz @ZrrSkywalker 非常感谢你们的分享解答，祝你们学习生活愉快！
